### PR TITLE
add ^ to operators options

### PR DESCRIPTION
**Pull request by AshimeeAlt**

### CODE REVIEW

**Comment by Ianyourgod** [comment]
the switch case is useless.
just use an if
switch cases are good for speed with like a lot of things, not just 1 and a default

**Comment by Ianyourgod** [comment]
you wrote ;et [...]

**Comment by RedMan13** [comment]
> the switch case is useless. just use an if switch cases are good for speed with like a lot of things, not just 1 and a default
me when planned expansion :trollface:

**Comment by Ianyourgod** [comment]
alr this should be fine, ill merge now

**Comment by Ianyourgod** [comment]
> > the switch case is useless. just use an if switch cases are good for speed with like a lot of things, not just 1 and a default
> > me when planned expansion :trollface:

When is this block gonna need expansion

**Comment by RedMan13** [comment]
whenever they want :bleh

**Pull request merged**
