### PR TITLE
add is key pressed block

### PR DESCRIPTION
**Pull request by PuzzlingGGG**
uhh yeah its pretty simple

### CODE REVIEW

**Comment by PuzzlingGGG** [comment]
wtf where is it man im too tired for this

**Comment by Ianyourgod** [comment]
you have to add it to the uh

**Comment by Ianyourgod** [comment]
its an xml file

**Comment by Ianyourgod** [comment]
i forgor the name

**Comment by PuzzlingGGG** [comment]
buuuuu

**Pull request closed without merging**
